[site]
title = "Nathan Gill"
author = "Nathan Gill <nathan.j.gill@outlook.com>"
description = "Nathan Gill's personal website"
base_url = "https://nathanjgill.uk/"
default_template = "page.html"

[build]
include_drafts = false
static_prefix = ""
plugin_dir = "plugins"

[serve]
host = "0.0.0.0"
port = 8080
auto_reload = false

[[plugin]]
name = "rss_generator.py"
hook = "post"
hash = "6b60b88d72590dafa5f91f17d5055f3e261f447de9f77187b9453bbd01605b5a"
build_dir = "build"
rss_file = "rss.xml"
content_dir = "content"
post_dir = "posts"
title = "Nathan Gill's Blog"
url = "https://nathanjgill.uk/"
desc = "Nathan Gill's blog posts on various topics"

[[plugin]]
name = "sitemap_generator.py"
hook = "post"
hash = "08b8b997a56349ef22ae0054bc9d35075a36dc1febc9bca6392a021cb369dd8b"
